/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yassine
 */
 import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
public class Add_student extends javax.swing.JFrame {
    String sql ="insert into student values (?,?,?,?)";
    /**
     * Creates new form Add_student
     */
    public Add_student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        group = new javax.swing.JTextField();
        last = new javax.swing.JTextField();
        t_id = new javax.swing.JLabel();
        t_id1 = new javax.swing.JLabel();
        t_id3 = new javax.swing.JLabel();
        t_id2 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 230, 40));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 230, 40));
        getContentPane().add(group, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 230, 40));
        getContentPane().add(last, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 230, 40));

        t_id.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        t_id.setText("Student ID");
        getContentPane().add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, -1));

        t_id1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        t_id1.setText("Student Name");
        getContentPane().add(t_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, -1, -1));

        t_id3.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        t_id3.setText("Group");
        getContentPane().add(t_id3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        t_id2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        t_id2.setText("Student Last Name");
        getContentPane().add(t_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        cancel.setBackground(new java.awt.Color(204, 204, 255));
        cancel.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 130, 60));

        Back.setBackground(new java.awt.Color(204, 204, 255));
        Back.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 60));

        confirm.setBackground(new java.awt.Color(204, 204, 255));
        confirm.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/abstract-connections-banner-design-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        id.setText("");
        name.setText("");
        last.setText("");
    }//GEN-LAST:event_cancelActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Admin a = new Admin();
        a.show();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/student_management_system","root","12345") ;
                PreparedStatement ps= c.prepareStatement(sql);
                ps.setInt(1,Integer.parseInt(id.getText()));
                ps.setString(2,name.getText());
                ps.setString(3,last.getText());
                ps.setString(4,group.getText().toUpperCase());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null,"Insertion successful");
                c.close();
            } catch (SQLException ex) {
                Logger.getLogger(Add_teacher.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,ex);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Add_teacher.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField group;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField last;
    private javax.swing.JTextField name;
    private javax.swing.JLabel t_id;
    private javax.swing.JLabel t_id1;
    private javax.swing.JLabel t_id2;
    private javax.swing.JLabel t_id3;
    // End of variables declaration//GEN-END:variables
}
