/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yassine
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        DelS1 = new javax.swing.JButton();
        DelS2 = new javax.swing.JButton();
        DelS = new javax.swing.JButton();
        AddS = new javax.swing.JButton();
        DelT = new javax.swing.JButton();
        AddT = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        Login.setText("Select option");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        DelS1.setBackground(new java.awt.Color(204, 204, 255));
        DelS1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        DelS1.setText("Students List");
        DelS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelS1ActionPerformed(evt);
            }
        });
        getContentPane().add(DelS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 210, -1));

        DelS2.setBackground(new java.awt.Color(204, 204, 255));
        DelS2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        DelS2.setText("Teachers List");
        DelS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelS2ActionPerformed(evt);
            }
        });
        getContentPane().add(DelS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 210, -1));

        DelS.setBackground(new java.awt.Color(204, 204, 255));
        DelS.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        DelS.setText("Delete Student");
        DelS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelSActionPerformed(evt);
            }
        });
        getContentPane().add(DelS, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 210, -1));

        AddS.setBackground(new java.awt.Color(204, 204, 255));
        AddS.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        AddS.setText("Add Student");
        AddS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSActionPerformed(evt);
            }
        });
        getContentPane().add(AddS, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 210, -1));

        DelT.setBackground(new java.awt.Color(204, 204, 255));
        DelT.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        DelT.setText("Delete Teacher");
        DelT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelTActionPerformed(evt);
            }
        });
        getContentPane().add(DelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 210, -1));

        AddT.setBackground(new java.awt.Color(204, 204, 255));
        AddT.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        AddT.setText("Add Teacher");
        AddT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTActionPerformed(evt);
            }
        });
        getContentPane().add(AddT, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 210, -1));

        Back.setBackground(new java.awt.Color(204, 204, 255));
        Back.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/abstract-connections-banner-design-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTActionPerformed
        // TODO add your handling code here:
        Add_teacher a = new Add_teacher();
        a.show();
        dispose();
    }//GEN-LAST:event_AddTActionPerformed

    private void AddSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSActionPerformed
        // TODO add your handling code here:
            Add_student as = new Add_student();
            as.show();
            dispose();
    }//GEN-LAST:event_AddSActionPerformed

    private void DelTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelTActionPerformed
        // TODO add your handling code here:
        Delete_teacher dt = new Delete_teacher();
        dt.show();
        dispose();
        
    }//GEN-LAST:event_DelTActionPerformed

    private void DelSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelSActionPerformed
        // TODO add your handling code here:
        Delete_student ds=new Delete_student();
        ds.show();
        dispose();
    }//GEN-LAST:event_DelSActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        RoleSelect a = new RoleSelect();
        a.show();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void DelS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelS1ActionPerformed
       Students_list sl = new Students_list();
       sl.show();
       dispose();
    }//GEN-LAST:event_DelS1ActionPerformed

    private void DelS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelS2ActionPerformed
        Teacher_list tl = new Teacher_list();
        tl.show();
        dispose();
    }//GEN-LAST:event_DelS2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddS;
    private javax.swing.JButton AddT;
    private javax.swing.JButton Back;
    private javax.swing.JButton DelS;
    private javax.swing.JButton DelS1;
    private javax.swing.JButton DelS2;
    private javax.swing.JButton DelT;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
