/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Yassine
 */
public class Connect_as extends javax.swing.JFrame {
    String admin = "yassine";
    String password="12345";
    /**
     * Creates new form Connect_as
     */
    public Connect_as() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userlabel = new javax.swing.JLabel();
        passlabel = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        Login = new javax.swing.JLabel();
        errormsg = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user.gif"))); // NOI18N
        getContentPane().add(userlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, 60));

        passlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-password.gif"))); // NOI18N
        getContentPane().add(passlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 50, 60));

        user.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 230, 40));

        cancel.setBackground(new java.awt.Color(204, 204, 255));
        cancel.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 130, 60));

        confirm.setBackground(new java.awt.Color(204, 204, 255));
        confirm.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 130, 60));

        Login.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
        Login.setText("Login");
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        errormsg.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        errormsg.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(errormsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        pass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 230, 40));

        Back.setBackground(new java.awt.Color(204, 204, 255));
        Back.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/abstract-connections-banner-design-vector.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        // TODO add your handling code here:
        if(user.getText().equals(admin) && pass.getText().equals(password))
        {
            Admin a = new Admin();
            a.show();
            dispose();
        }
        else
        {
            errormsg.setText("User name or password is incorrect !");
        }
    }//GEN-LAST:event_confirmActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        user.setText("");
        pass.setText("");
    }//GEN-LAST:event_cancelActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        RoleSelect a = new RoleSelect();
        a.show();
        dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Connect_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Connect_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Connect_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Connect_as.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Connect_as().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Login;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JLabel errormsg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel passlabel;
    private javax.swing.JTextField user;
    private javax.swing.JLabel userlabel;
    // End of variables declaration//GEN-END:variables
}
